// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3559fa81f7e175927f379e84a9ff7cb3d8e4301edbcf9d63f34000dac5b3df3d'>;
export type ExecutionHash =
  ExecutionHashBase<'5e01556876ff4ecb3927a821b40925fc3ba19a965659d301e2e7833ab45f94cc'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8number@1';
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: 'pg/int8@1';
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': {
        readonly output: 'pg/char@1';
        readonly nullable: true;
      };
      readonly 'pg/date-string@1': {
        readonly output: 'pg/date-string@1';
        readonly nullable: true;
      };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': {
        readonly output: 'pg/enum@1';
        readonly nullable: true;
      };
      readonly 'pg/float@1': {
        readonly output: 'pg/float@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/inet@1': {
        readonly output: 'pg/inet@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int2@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int4@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/text-array@1': {
        readonly output: 'pg/text-array@1';
        readonly nullable: true;
      };
      readonly 'pg/text@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/time-string@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': {
        readonly output: 'pg/timetz@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
      readonly 'sql/char@1': {
        readonly output: 'sql/char@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'sql/float@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'sql/int@1';
        readonly nullable: true;
      };
      readonly 'sql/text@1': {
        readonly output: 'sql/text@1';
        readonly nullable: true;
      };
      readonly 'sql/varchar@1': {
        readonly output: 'pg/text@1';
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/float4@1': {
        readonly output: 'pg/float4@1';
        readonly nullable: true;
      };
      readonly 'pg/float8@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'pg/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
      readonly 'pg/interval@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/numeric@1': {
        readonly output: 'pg/numeric@1';
        readonly nullable: true;
      };
      readonly 'pg/time-string@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/interval@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': {
        readonly output: 'pg/float8@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8number@1';
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int2@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int4@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
      readonly 'pg/int8@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/int8number@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': {
        readonly output: 'pg/int8@1';
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Permission: {
      readonly code: Varchar<100>;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: Varchar<500> | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly scopePolicy: 'global_only' | 'location_or_global';
    };
    readonly Role: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: Varchar<500> | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly isProtected: CodecTypes['pg/bool@1']['output'];
      readonly name: Varchar<120>;
      readonly scopeType: 'global' | 'location';
      readonly systemKey: Varchar<80> | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly RolePermission: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly permissionId: CodecTypes['pg/int8@1']['output'];
      readonly roleId: CodecTypes['pg/int8@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Permission: {
      readonly code: CodecTypes['sql/varchar@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly scopePolicy: 'global_only' | 'location_or_global';
    };
    readonly Role: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly isProtected: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly scopeType: 'global' | 'location';
      readonly systemKey: CodecTypes['sql/varchar@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly RolePermission: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly permissionId: CodecTypes['pg/int8@1']['input'];
      readonly roleId: CodecTypes['pg/int8@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly permissions: {
      readonly code: Varchar<100>;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: Varchar<500> | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly scope_policy: 'global_only' | 'location_or_global';
    };
    readonly role_permissions: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly permission_id: CodecTypes['pg/int8@1']['output'];
      readonly role_id: CodecTypes['pg/int8@1']['output'];
    };
    readonly roles: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: Varchar<500> | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly is_protected: CodecTypes['pg/bool@1']['output'];
      readonly name: Varchar<120>;
      readonly scope_type: 'global' | 'location';
      readonly system_key: Varchar<80> | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly permissions: {
      readonly code: CodecTypes['sql/varchar@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly scope_policy: 'global_only' | 'location_or_global';
    };
    readonly role_permissions: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly permission_id: CodecTypes['pg/int8@1']['input'];
      readonly role_id: CodecTypes['pg/int8@1']['input'];
    };
    readonly roles: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly is_protected: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly scope_type: 'global' | 'location';
      readonly system_key: CodecTypes['sql/varchar@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Permission = {
    code: Varchar<100>;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    description: Varchar<500> | null;
    id: CodecTypes['pg/int8@1']['output'];
    scopePolicy: 'global_only' | 'location_or_global';
    rolePermissions: public_RolePermission[];
    readonly [RelationKeys]?: 'rolePermissions';
  };
  export type public_Role = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    description: Varchar<500> | null;
    id: CodecTypes['pg/int8@1']['output'];
    isProtected: CodecTypes['pg/bool@1']['output'];
    name: Varchar<120>;
    scopeType: 'global' | 'location';
    systemKey: Varchar<80> | null;
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    rolePermissions: public_RolePermission[];
    readonly [RelationKeys]?: 'rolePermissions';
  };
  export type public_RolePermission = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    permissionId: CodecTypes['pg/int8@1']['output'];
    roleId: CodecTypes['pg/int8@1']['output'];
    permission: public_Permission;
    role: public_Role;
    readonly [RelationKeys]?: 'permission' | 'role';
  };
}

export declare const models: {
  public: {
    Permission: Models.public_Permission;
    Role: Models.public_Role;
    RolePermission: Models.public_RolePermission;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly permissions: {
              columns: {
                readonly code: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly description: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 500 };
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly scope_policy: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['code'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly role_permissions: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly permission_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
                readonly role_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['role_id', 'permission_id'];
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'role_permissions_permission_id_idx_909cec36';
                  readonly prefix: 'role_permissions_permission_id_idx';
                  readonly columns: readonly ['permission_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'role_permissions_role_id_idx_d9467c50';
                  readonly prefix: 'role_permissions_role_id_idx';
                  readonly columns: readonly ['role_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'role_permissions';
                    readonly columns: readonly ['role_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'roles';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'role_permissions';
                    readonly columns: readonly ['permission_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'permissions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly roles: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'now()';
                  };
                };
                readonly description: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 500 };
                };
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly is_protected: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 120 };
                };
                readonly scope_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly system_key: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 80 };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['name'] },
                { readonly columns: readonly ['system_key'] },
                { readonly columns: readonly ['id', 'scope_type'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly PermissionScopePolicy: {
              readonly kind: 'valueSet';
              readonly values: readonly ['global_only', 'location_or_global'];
            };
            readonly RoleScopeType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['global', 'location'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly permissions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Permission';
    };
    readonly role_permissions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RolePermission';
    };
    readonly roles: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Role';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Permission: {
            readonly fields: {
              readonly code: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 500 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int8@1';
                };
              };
              readonly scopePolicy: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
            };
            readonly relations: {
              readonly rolePermissions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RolePermission';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['permissionId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'permissions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly code: { readonly column: 'code' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly scopePolicy: { readonly column: 'scope_policy' };
              };
            };
          };
          readonly Role: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 500 };
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int8@1';
                };
              };
              readonly isProtected: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/bool@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 120 };
                };
              };
              readonly scopeType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/text@1';
                };
              };
              readonly systemKey: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 80 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly rolePermissions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RolePermission';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['roleId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'roles';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly description: { readonly column: 'description' };
                readonly id: { readonly column: 'id' };
                readonly isProtected: { readonly column: 'is_protected' };
                readonly name: { readonly column: 'name' };
                readonly scopeType: { readonly column: 'scope_type' };
                readonly systemKey: { readonly column: 'system_key' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly RolePermission: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly permissionId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int8@1';
                };
              };
              readonly roleId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/int8@1';
                };
              };
            };
            readonly relations: {
              readonly permission: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Permission';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['permissionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly role: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Role';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['roleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'role_permissions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly permissionId: { readonly column: 'permission_id' };
                readonly roleId: { readonly column: 'role_id' };
              };
            };
          };
        };
        readonly enum: {
          readonly PermissionScopePolicy: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'GlobalOnly'; readonly value: 'global_only' },
              {
                readonly name: 'LocationOrGlobal';
                readonly value: 'location_or_global';
              },
            ];
          };
          readonly RoleScopeType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'Global'; readonly value: 'global' },
              { readonly name: 'Location'; readonly value: 'location' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: {
            readonly id: 'timestampNow';
            readonly kind: 'generator';
          };
          readonly onUpdate: {
            readonly id: 'timestampNow';
            readonly kind: 'generator';
          };
          readonly ref: {
            readonly entry: 'roles';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
